language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-22
    - python: 3.6
      env: TOXENV=py36-30
    - python: 3.7
      env: TOXENV=py37-22
    - python: 3.7
      env: TOXENV=py37-30
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox -e $TOXENV
# containers
sudo: false
