language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-111
    - python: 3.6
      env: TOXENV=py36-20
    - python: 3.7
      env: TOXENV=py36-111
    - python: 3.7
      env: TOXENV=py36-20
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox -e $TOXENV
# containers
sudo: false
